<?php
include("./tianyi.php");
$data=$_REQUEST;
if($data["key"]!=$apikey)
{
die("密钥不正确");
}else if($data["do"]=="get")
{
if($data["get"]=="ggsitename")
{
if(empty($data["msg"]))
{
die("请求参数错误");
}else{
$info=file_get_contents("./tianyi.php");
$info=str_replace($ming,$data["msg"],$info);
print_r($info);
file_put_contents("./tianyi.php",$info);
die("修改成功！");
}
}else if($data["get"]=="sitename")
{
die("获取类型：获取网站名称\n获取内容：$ming");
}
if($data["get"]=="ggemail")
{
if(empty($data["msg"]))
{
die("请求参数错误");
}else{
$info=file_get_contents("./tianyi.php");
$info=str_replace($youxiang,$data["msg"],$youxiang);
print_r($info);
file_put_contents("./tianyi.php",$info);
die("修改成功！");
}
}else if($data["get"]=="email")
{
die("获取类型：获取网站站长邮箱\n获取内容：$youxiang");
}
if($data["get"]=="ggkefu")
{
if(empty($data["msg"]))
{
die("请求参数错误");
}else{
$info=file_get_contents("./tianyi.php");
$info=str_replace($kefu,$data["msg"],$kefu);
print_r($info);
file_put_contents("./tianyi.php",$info);
die("修改成功！");
}
}else if($data["get"]=="kefu")
{
die("获取类型：获取网站站长QQ号\n获取内容：$kefu");
}else if($data["get"]=="email")
{
die("获取类型：获取网站站长邮箱\n获取内容：$youxiang");
}
if($data["get"]=="ggxiaoyu")
{
if(empty($data["msg"]))
{
die("请求参数错误");
}else{
$info=file_get_contents("./tianyi.php");
$info=str_replace($xiaoyu,$data["msg"],$xiaoyu);
print_r($info);
file_put_contents("./tianyi.php",$info);
die("修改成功！");
}
}else if($data["get"]=="xiaoyu")
{
die("获取类型：获取网站官方群号\n获取内容：$xiaoyu");
if($data["get"]=="ggqun")
{
if(empty($data["msg"]))
{
die("请求参数错误");
}else{
$info=file_get_contents("./tianyi.php");
$info=str_replace($qun,$data["msg"],$qun);
print_r($info);
file_put_contents("./tianyi.php",$info);
die("修改成功！");
}
}else if($data["get"]=="qun")
{
die("获取类型：获取网站官方群链接\n获取内容：$qun");
}
}
}